// Navigation-only mapping for accessibility.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/accessibility.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../accessibility.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de loginpagina is geopend");
Then("hebben e-mail, wachtwoord en inlogknop een programmatisch gekoppeld label");
When("er met Tab door het formulier wordt genavigeerd");
Given("de administrator is ingelogd");
Then("heeft elke hoofdnavigatieknop een herkenbare, unieke naam");
When("de eerste hoofdnavigatieknop via het toetsenbord wordt bediend");
Given("toegankelijkheid en toetsenbordbediening is voorbereid");
When("de flow voor A11Y-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat lopende tekst blijft op een breed scherm leesbaar van regellengte");
