// Navigation-only mapping for accessibility.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/accessibility.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../accessibility.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de loginpagina is geopend");
Then("hebben e-mail, wachtwoord en inlogknop een programmatisch gekoppeld label");
When("er met Tab door het formulier wordt genavigeerd");
Given("de administrator is ingelogd");
Then("heeft elke hoofdnavigatieknop een herkenbare, unieke naam");
When("de eerste hoofdnavigatieknop via het toetsenbord wordt bediend");
Given("toegankelijkheid en toetsenbordbediening is voorbereid");
When("de flow voor A11Y-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat lopende tekst blijft op een breed scherm leesbaar van regellengte");
Given("de administrator opent de voorbeeld-herstel-dialoog");
Then("is de sluitknop bereikbaar en gelabeld, en ligt de focus in de dialoog");
When("Escape wordt ingedrukt");
Then("sluit de dialoog en gaat de focus niet verloren op de body");
When("de flow voor A11Y-H-005 wordt uitgevoerd");
Then("geeft de basisregel een outline aan button, input, select, textarea, a, summary en tabindex");
And("een via het toetsenbord gefocuste navigatieknop toont echt een outline");
Given("de administrator is ingelogd op een korte viewport");
When("de flow voor A11Y-H-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de sluitknop van een scrollende dialoog blijft in beide skins in beeld");
