// Navigation-only mapping for organization-settings.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/admin-writes.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../admin-writes.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("organisatie-instellingen beheren is voorbereid");
When("de flow voor ADM-WR-H-001 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin kan company/settings server-led opslaan");
When("de flow voor ADM-WR-H-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin kan beheerder server-led aanmaken en wijzigen");
When("de flow voor ADM-WR-H-014 wordt uitgevoerd");
Then("draagt alleen de boekhouding een eigen tekst");
And("blijft de salarisroute leeg, zodat die de opdrachttekst blijft erven");
When("de flow voor ADM-WR-H-013 wordt uitgevoerd");
Then("leest de bootstrap exact wat er is ingevuld terug");
When("de flow voor ADM-WR-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin kan medewerker server-led aanmaken en bootstrap ziet deze terug");
When("de flow voor ADM-WR-N-001 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat dubbel accountadres geeft veilige metadata van het bestaande bedrijfsaccount");
When("de flow voor ADM-WR-N-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat beheerder aanmaken met het e-mailadres van een bestaande medewerker wordt geweigerd");
Given("er al een medewerker met een vast e-mailadres bestaat");
When("een beheerder wordt aangemaakt met exact datzelfde adres");
Then("verschijnt een blokkade-popup en wordt de bestaande medewerker uitgelicht, i.p.v. stil niets te doen");
And("na sluiten is er niets aangemaakt en is het bestaande account uitgelicht");
When("de flow voor ADM-WR-N-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat dubbel accountadres opent het bestaande account zonder duplicaat");
When("de flow voor ADM-WR-H-004 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin slaat medewerker zonder SMTP veilig op met toegang in afwachting");
When("de flow voor ADM-WR-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat productie toont uitsluitend serveraccounts en opent medewerkerformulier bovenaan");
Given("de server een actief gebruikersaccount en actief medewerkersprofiel teruggeeft");
When("de beheerder de medewerker deactiveert");
Then("verdwijnt de medewerker uit Actief en staat deze onder Inactief");
And("definitief verwijderen haalt het lege account uit Teambeheer");
When("de flow voor ADM-WR-H-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat serverwrite na Herstel verschijnt direct in Teambeheer");
When("de flow voor ADM-WR-H-008 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat bestaande beheerder en medewerker worden na Herstel direct terug in Teambeheer getoond");
Given("de administrator is ingelogd en reset naar vaste baseline");
When("actionable admin tasks bestaan in de workflow");
Then("zijn taken chronologisch gesorteerd (validatie van fix)");
Given("de administrator een nieuwe beheerder en medewerker server-led opslaat (geen gemockte API)");
When("de pagina echt opnieuw wordt geladen (F5), niet alleen opnieuw gerenderd");
Then("blijven de nieuwe beheerder en medewerker zichtbaar in Teambeheer");
Given("de administrator Instellingen heeft geopend");
When("de pagina echt opnieuw wordt geladen (F5)");
Then("blijft Instellingen actief in plaats van terug te vallen op Dashboard");
Given("de administrator is ingelogd en Teambeheer heeft geopend");
When("een nieuwe beheerder met dezelfde naam maar een uniek adres wordt opgeslagen");
Then("wordt het account direct aangemaakt, zonder tussenvraag over de naam");
Given("er al een beheerder én een medewerker bestaan met verschillende namen");
When("een nieuwe beheerder met dezelfde naam én het e-mailadres van de medewerker wordt opgeslagen");
Then("komt er geen tussenvraag over de naam en blokkeert de server hard op het al gebruikte e-mailadres");
When("een medewerker en een beheerder worden toegevoegd, telt het totaal telkens precies 1 op t.o.v. daarvóór");
Then("verandert een poging met exact hetzelfde e-mailadres het totaal niet");
And("een volledig uniek account telt precies 1 op, zonder dat er verder iets bijkomt");
Given("Teambeheer de serverstand toont zonder melding");
When("de administrator Herstel gebruikt en terugkeert naar Teambeheer");
Then("verklaart een zichtbare melding dat deze telling niet van de server komt");
And("de knop haalt de echte serverstand terug en laat de melding verdwijnen");
When("de flow voor ADM-WR-H-017 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een ontvangerslijst terugsturen zoals hij binnenkwam verandert niets");
When("de beheerder bij een medewerker een nieuwe ontvanger toevoegt");
Then("staat hij bij die medewerker aan");
And("staat hij bij een andere medewerker niet aan");
And("een ontvanger die via Instellingen wordt toegevoegd staat nergens aan");
Given("het formulier de twee velden toont, ook bij een nieuwe ontvanger");
When("onderwerp, tekst en een eigen tekst voor een ontvanger worden ingevuld");
Then("staat alles er na een F5 nog steeds");
And("opslaan werkt ook als er verder niets aan het account verandert");
When("het brokervinkje wordt omgezet en opgeslagen");
Then("staat het na een herlaad nog steeds zo");
