// Navigation-only mapping for admin-writes.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/admin-writes.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("beheer- en instellingenwijzigingen via API is voorbereid");
When("de flow voor ADM-WR-H-001 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin kan company/settings server-led opslaan");
When("de flow voor ADM-WR-H-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin kan beheerder server-led aanmaken en wijzigen");
When("de flow voor ADM-WR-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin kan medewerker server-led aanmaken en bootstrap ziet deze terug");
When("de flow voor ADM-WR-H-004 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat admin slaat medewerker zonder SMTP veilig op met toegang in afwachting");
