// Navigation-only mapping for announcements.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/announcements.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../announcements.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een actieve medewerker als ontvanger");
When("de beheerder de mededeling verstuurt");
Then("wordt met Playwright-assertions bevestigd dat beheerder verstuurt een mededeling aan een gekozen medewerker");
Given("de beheerder een concept opslaat");
And("alleen een concept mag definitief worden verwijderd");
When("de flow voor ANN-H-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een concept blijft intern en kan daarna definitief worden verwijderd");
Given("een verzonden mededeling");
When("de beheerder intrekt met een reden");
Then("staat het bericht als ingetrokken in de interne historie");
And("alleen een ingetrokken bericht mag bij medewerkers worden verborgen");
Given("mededelingen versturen, intrekken en verbergen is voorbereid");
When("de flow voor ANN-N-004 wordt uitgevoerd");
Then("geeft intrekken zonder reden een nette 400 en blijft het bericht verzonden");
When("de flow voor ANN-N-005 wordt uitgevoerd");
Then("wordt elk ontbrekend verplicht veld afzonderlijk gemeld");
When("de flow voor ANN-N-006 wordt uitgevoerd");
Then("krijgt een anonieme aanroep 401");
And("een ingelogde medewerker mag zelf niets versturen");
