// Navigation-only mapping for audit-log.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/audit-log.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../audit-log.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een ingelogde admin");
When("het auditlog wordt opgehaald");
Then("wordt met Playwright-assertions bevestigd dat admin kan auditlog ophalen");
When("gefilterd op entity_type=invoice");
Then("wordt met Playwright-assertions bevestigd dat auditlog filtert op entity_type");
When("gefilterd op event_type=invoice.locked");
Then("wordt met Playwright-assertions bevestigd dat auditlog filtert op event_type");
When("de flow voor AUD-H-004 wordt uitgevoerd");
Then("bevat geen enkel item een wachtwoord of token veld in event_data");
Given("geen sessie");
When("auditlog wordt opgevraagd");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker krijgt 401 op auditlog");
Given("een ingelogde medewerker");
When("auditlog wordt opgevraagd als medewerker");
Then("wordt met Playwright-assertions bevestigd dat medewerker mag auditlog niet lezen");
Given("auditlog en traceerbaarheid is voorbereid");
When("de flow voor AUD-H-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat auditlog combineert entity- en eventfilter");
When("de flow voor AUD-H-008 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat auditlog begrenst een nullimiet op een record");
When("de flow voor AUD-H-009 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat auditlog begrenst een hoge limiet op tweehonderd records");
When("de flow voor AUD-N-010 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat auditlog weigert POST");
