// Navigation-only mapping for auth.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/auth.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../auth.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de Path loginpagina beschikbaar is");
When("de administrator inlogt met geldige inloggegevens");
Then("auth/me bevestigt administrator sessie en juiste gebruiker");
And("F5 behoudt de geldige sessie zonder terugkeer naar accountkeuze");
When("de medewerker inlogt met geldige inloggegevens");
Then("auth/me bevestigt medewerkersessie en juiste gebruiker");
Given("een ingelogde Path gebruiker");
When("de gebruiker uitlogt");
Then("auth/me geeft authenticated false en geen actieve user");
Given("de lokale Path loginpagina beschikbaar is");
Then("de gekozen beheeraccount automatisch is ingevuld");
When("de gebruiker eenmaal op Inloggen klikt");
Then("het beheerdersdashboard opent");
Given("inloggen, uitloggen en sessiebeheer is voorbereid");
When("de flow voor AUTH-N-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat onbekend account geeft dezelfde generieke loginfout");
When("de flow voor AUTH-N-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat ongeldig e-mailformaat wordt als invalid-payload geweigerd");
Given("de testlogin gereed is zonder pagina-herlaad");
When("een andere medewerker via de zichtbare rolkeuze wordt gekozen");
Then("staan e-mail en medewerkerswachtwoord direct klaar zonder F5");
When("daarna een beheerder via de zichtbare rolkeuze wordt gekozen");
Then("wisselen e-mail en wachtwoord meteen naar het beheeraccount");
Given("vijf mislukte pogingen voor hetzelfde account zijn geregistreerd");
When("opnieuw via het loginformulier wordt geprobeerd");
Then("toont de UI de resterende blokkeertijd en blijft het formulier bruikbaar voor een ander account");
Given("het account door vijf mislukte pogingen is geblokkeerd");
When("de pagina met F5 wordt herladen");
Then("blijft de aflopende blokkade zichtbaar en blijft de server leidend");
Given("de administrator is ingelogd");
When("de pagina met F5 wordt herladen terwijl de sessiecontrole vertraagd is");
Then("blijft body.auth-booting actief en zijn beide shells onzichtbaar zolang de sessiecontrole loopt");
And("na afronden van de sessiecontrole verdwijnt auth-booting en toont alleen de juiste shell");
Then("heet het omgevingsveld Veilige testomgeving");
And("heet de lokale titel Welkom bij Path Uren & Facturatie");
When("dezelfde login als productiepresentatie wordt getoond");
Then("heten omgeving en titel Beveiligde omgeving en Inloggen");
When("de flow voor AUTH-H-020 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat elke medewerker ziet na inloggen de eigen naam, nooit die van een collega");
When("de flow voor AUTH-H-021 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat elke beheerder ziet na inloggen de eigen naam, nooit die van een collega");
When("de flow voor AUTH-H-022 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat in productiemodus toont de app de naam van de ingelogde gebruiker");
