// Navigation-only mapping for avatar-picker.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/avatar-picker.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../avatar-picker.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker inlogt zonder ooit een avatar gekozen te hebben");
When("de flow voor AVATAR-H-001 wordt uitgevoerd");
Then("toont het profielmenu meteen zijn vaste, toegewezen avatar (nummer 1)");
Given("de beheerder inlogt zonder ooit een avatar gekozen te hebben");
When("de flow voor AVATAR-H-002 wordt uitgevoerd");
Then("toont het profielmenu meteen zijn vaste, toegewezen avatar (nummer 96)");
Given("avatarkiezer in het profielmenu is voorbereid");
Then("bestaan alle bestaande menu-onderdelen nog steeds, ongewijzigd");
When("op de knopkop (avatar, naam, rol) wordt getikt");
Then("klapt een raster van twaalf avatars open, met paginateller 1/10");
When("negen keer op volgende wordt getikt (113 avatars = 9x12 + 5)");
Then("staat de teller op 10/10, met precies vijf avatars en een uitgeschakelde volgende-knop");
And("gaat één stap terug weer naar een volle pagina van twaalf");
When("een andere avatar dan de huidige wordt aangetikt");
Then("verschijnt de keuze meteen, blijft het menu open, en is er geen aparte opslaan-knop nodig");
And("staat dezelfde avatar er nog na een echte paginaherlading");
When("de flow voor AVATAR-N-001 wordt uitgevoerd");
Then("is de achtergrond van het vinkje mint en de tekstkleur navy, geen wit");
When("de flow voor AVATAR-H-006 wordt uitgevoerd");
Then("geeft dezelfde naam altijd dezelfde avatar-index terug, ook bij afwijkende spatiëring/hoofdletters");
And("blijven de zeven vaste collega-namen op hun afgesproken avatar staan, ook met afwijkende spatiëring/hoofdletters");
Given("de vormgeving op Nieuw staat");
When("het profielmenu en de avatarkiezer worden geopend");
Then("werkt de kiezer identiek: twaalf avatars, teller 1/10, en hetzelfde vinkje mint-op-navy");
And("blijft het menu open, net als in Klassiek");
