// Navigation-only mapping for customer-timesheets.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/customer-timesheet-api.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker is ingelogd in auth-modus");
When("de medewerker een concept uploadt en indient");
Then("de medewerker kan het ingediende document teruglezen en downloaden");
And("cleanup: wissel naar administrator-context voor reviewstappen");
Given("de administrator is ingelogd voor reviewbesluiten");
When("de administrator approve en request_resubmit uitvoert");
And("cleanup: sessie sluiten voor testisolatie");
Given("de medewerker is ingelogd");
When("de medewerker schrijft met een andere employee_id");
Then("wordt met Playwright-assertions bevestigd dat employee kan geen klanturenstaat voor andere medewerker wijzigen");
Given("de medewerker is ingelogd met een ingediende klanturenstaat");
When("de medewerker approve probeert uit te voeren");
Then("de medewerker ook geen request_resubmit mag uitvoeren");
Given("de medewerker is ingelogd met een concept klanturenstaat");
When("de medewerker mark_skipped uitvoert met reden");
Then("restore_missing zet de status terug naar missing");
When("de medewerker een tekstbestand uploadt als klanturenstaat");
Then("wordt met Playwright-assertions bevestigd dat employee krijgt 400 bij ongeldig bestandstype");
When("de medewerker een JPG uploadt als concept-klanturenstaat");
Then("is het opgeslagen document een geldig PDF, geen JPG");
When("de medewerker een PDF van ruim boven de 2 MB-limiet uploadt");
Then("wordt met Playwright-assertions bevestigd dat employee krijgt 400 bij een te grote klanturenstaat-upload");
