// Navigation-only mapping for customer-timesheets.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/customer-timesheet-api.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../customer-timesheet-api.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de beheerder is ingelogd bij een periode zonder klanturenstaatrecord");
When("de beheerder eerst zonder en daarna met verplichte reden extern bevestigt");
Then("de bevestiging auditbaar leesbaar is en door de beheerder kan worden teruggedraaid");
Given("klanturenstaten en documentverwerking is voorbereid");
When("de flow voor CTS-API-H-009 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat brokerroute koppelt de officiële klanturenstaat aan dezelfde medewerker en periode");
Given("de medewerker is ingelogd in auth-modus");
When("de medewerker een concept uploadt en indient");
Then("de medewerker kan het ingediende document teruglezen en downloaden");
And("cleanup: wissel naar administrator-context voor reviewstappen");
Given("de administrator is ingelogd voor reviewbesluiten");
When("de administrator approve en request_resubmit uitvoert");
And("cleanup: sessie sluiten voor testisolatie");
Given("de medewerker is ingelogd");
When("de medewerker schrijft met een andere employee_id");
Then("wordt met Playwright-assertions bevestigd dat employee kan geen klanturenstaat voor andere medewerker wijzigen");
Given("de medewerker is ingelogd met een ingediende klanturenstaat");
When("de medewerker approve probeert uit te voeren");
Then("de medewerker ook geen request_resubmit mag uitvoeren");
Given("de medewerker is ingelogd met een concept klanturenstaat");
When("de medewerker mark_skipped uitvoert met reden");
Then("restore_missing zet de status terug naar missing");
When("de medewerker een tekstbestand uploadt als klanturenstaat");
Then("wordt met Playwright-assertions bevestigd dat employee krijgt 400 bij ongeldig bestandstype");
When("de medewerker een JPG uploadt als concept-klanturenstaat");
Then("is de JPG als inline bekijkbare PDF met een PDF-bestandsnaam opgeslagen");
When("de medewerker het concept vervangt door een PNG");
Then("is ook de PNG als inline bekijkbare PDF opgeslagen");
Given("de medewerker via de zichtbare upload een PNG als concept opslaat");
When("dezelfde medewerker opnieuw inlogt en via de zichtbare maandkeuze dezelfde periode opent");
Then("verschijnt het serverdocument en levert Klanturenstaat bekijken een inline PDF-response");
And("cleanup: zet de geïsoleerde toekomstcase terug naar ontbrekend en log uit");
When("de medewerker een PDF van ruim boven de 2 MB-limiet uploadt");
Then("wordt met Playwright-assertions bevestigd dat employee krijgt 400 bij een te grote klanturenstaat-upload");
Given("de medewerker is ingelogd en de bestaande klanturenstaat is vastgelegd");
When("de medewerker corrupte bytes met een JPG-bestandsnaam uploadt");
And("een afbeelding boven de veilige dimensiegrens wordt geweigerd");
Then("worden tekstbytes met alleen een PDF-bestandsnaam ook geweigerd");
Then("blijft het bestaande document ongewijzigd");
