// Navigation-only mapping for dashboard.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/dashboard.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../dashboard.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de administrator is ingelogd");
When("de administrator het dashboard opent");
Then("het dashboard toont admin-overzicht zonder consolefouten");
Given("de medewerker is ingelogd");
When("de medewerker het dashboard opent");
Then("alleen medewerkersinformatie wordt getoond zonder consolefouten");
Given("een oude serverstate en een afwijkend API-totaal van 205");
When("de flow voor DASH-N-007 wordt uitgevoerd");
Then("alle zichtbare totalen blijven gelijk aan de concrete taakregels");
Given("auth-modus met oude fallback-state en afwijkende serverwerkvoorraad");
When("voorbeeldgegevens worden hersteld");
Then("blijven de concrete taakregels leidend en verschijnt geen oude teller");
Given("Backoffice de voorbeeldomgeving herstelt en daarna naar Stasjo wisselt");
When("Stasjo daarna een open urenactie indient");
And("Stasjo voert daarna F5 uit");
Then("blijft de gewijzigde lokale teller zichtbaar en wordt er geen oude serverstatus teruggezet");
And("Backoffice kan Marc zijn klanturenstaat goedkeuren zonder statusrace");
Given("de administrator is ingelogd en reset naar vaste baseline");
When("een actionable urencontrole-taak (hours-review) wordt goedgekeurd");
Then("blijft de goedgekeurde taak weg en de teller stabiel na F5");
Given("de lokale demo toont alle 12 beginacties en tellerverdeling");
When("medewerkers alle vijf wachtende acties via de zichtbare interface afronden");
And("Backoffice bevestigt iedere resterende zichtbare taak tot de werkvoorraad 0 is");
Then("wordt met Playwright-assertions bevestigd dat gUI-closeout verwerkt alle 12 voorbeeldtaken via medewerker en Backoffice");
Given("de medewerker zit op het dashboard en timesheet-read is gemonitord");
When("de medewerker augustus-juli-augustus doorloopt vanuit dashboard");
Then("blijft de teller gelijk en zijn er geen verborgen timesheet-reads");
Given("de vaste GUI-baseline met twaalf open acties en zes actieve accounts");
When("de flow voor DASH-H-012 wordt uitgevoerd");
Then("toont het dashboard zeven Backoffice-acties en vijf wachttaken zonder medewerkerbadge in het menu");
And("Teambeheer toont vier medewerkers en twee beheerders als zes actieve accounts");
And("Dashboard opent bovenaan terwijl eigenaarbolletjes gericht naar hun werkvoorraad springen");
Given("Backoffice de vaste augustusbaseline opent");
When("de flow voor DASH-H-013 wordt uitgevoerd");
Then("toont klanturenstaten een verkoopklaar kaartenoverzicht");
And("proces en team tonen zonder lege tussenruimte duidelijke kerninformatie en acties");
Given("een medewerker die een urenstaat vult en het thema wisselt");
When("de medewerker uren invult en terug naar het medewerkerdashboard gaat");
Then("blijven de maandnamen zichtbaar in donkere modus");
Given("een medewerker op donker thema die vanuit dashboard naar uren gaat");
When("de medewerker uren wijzigt en terug navigeert via de zichtbare medewerkerroute");
Then("zijn de maandlabels nog zichtbaar in de maandkiezer");
Given("een medewerker met open maanden");
When("het medewerkerdashboard opent");
Then("is er een compacte open-maandenkaart zichtbaar met een directe maandknop");
Given("een medewerker met meerdere open acties over verschillende maanden");
When("het dashboard de werkvoorraad prioriteert");
Then("opent de hoofdactie exact de geprioriteerde maand en juiste taakroute");
Given("alleen augustus zowel een urencorrectie als documentherindiening vraagt");
When("de flow voor DASH-N-015 wordt uitgevoerd");
Then("staat de urencorrectie vóór het document en kloppen de totalen");
And("bij een volledig afgeronde werkvoorraad verdwijnen taaklijst en prioriteitsdata");
Given("juli als goedgekeurde verborgen urenstaat is achtergebleven");
When("het dashboard augustus prioriteert en Open correctie wordt gekozen");
Then("toont Mijn uren augustus als bewerkbare correctie met herindienknop");
Given("een medewerker zonder open acties in een lege toekomstmaand");
When("de medewerker een toekomstige maand probeert te openen");
Then("verschijnt september niet als open medewerkermaand");
Given("een medewerker die een toekomstige maand probeert te openen");
When("de medewerker teruggaat naar het dashboard");
Then("staat de periode op augustus en toont het overzicht geen toekomstige maanden");
Given("Backoffice met de volledige serverwerkvoorraad is ingelogd");
When("Backoffice augustus-juli-augustus doorloopt");
Then("blijven globale aantallen, eigenaren en taakidentiteiten gelijk");
And("eigenaarfilters openen alleen hun concrete taakregels");
And("opnieuw openen zet alle maandblokken terug naar ingeklapt");
