// Navigation-only mapping for database-integrity.feature.
// Database smoke remains executable through the SQL runner; no Cucumber runner is used.
// Generated by npm run docs:sync; executable SQL remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;

Given("de database CRUD smoke is voorbereid");
When("het SQL-script wordt uitgevoerd via de DB smoke runner");
Then("wordt het verwachte cleanup-result bevestigd");
