// Navigation-only mapping for database-relations.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/database-integrity.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../database-integrity.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("relationele database-integriteit is voorbereid");
When("de flow voor DB-H-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat geen enkele kerntabel bevat een weesverwijzing");
When("de flow voor DB-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de afhankelijke tabellen hebben de beloofde ON DELETE CASCADE");
Given("een net aangemaakte medewerker met opdracht en mailroute");
When("de beheerder de medewerker deactiveert en definitief verwijdert");
Then("bestaat er geen enkele rij meer die naar die medewerker verwijst");
