// Navigation-only mapping for mail-delivery.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/email-queue.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de admin heeft een factuur gelockt");
When("de flow voor EQ-H-001 wordt uitgevoerd");
Then("zijn er queue-items voor deze factuur met dry_run=true en status queued");
And("cleanup");
Given("een gelockte factuur met broker_invoice_attachment=true");
When("de queue wordt uitgelezen");
Then("heeft de broker-channel attachment_policy=invoice_and_customer_timesheet");
Given("een gelockte factuur waar payroll_invoice_attachment=false");
When("de queue-items voor deze factuur worden uitgelezen");
Then("heeft elke EasySalary-item attachment_policy=none");
Given("één goedgekeurde urenstaat als factuur is afgerond");
When("de drie functionele routes voor dezelfde factuur worden uitgelezen");
Then("wordt met Playwright-assertions bevestigd dat één factuuractie maakt drie gescheiden mailroutes met het juiste bijlagenbeleid");
Given("een admin is ingelogd met een reeds gelockte factuur");
When("action=enqueue wordt aangeroepen");
Then("zijn de nieuwe items in de queue zichtbaar per invoiceId");
Given("een admin is ingelogd");
Then("wordt met Playwright-assertions bevestigd dat action=list response bevat verplichte velden");
Given("een beheerder is beveiligd ingelogd");
When("de beheerder het verzendoverzicht in Instellingen opent");
Then("zijn ontvanger, onderwerp, status, tijd en bijlagen zichtbaar zonder geheime inhoud");
And("Vernieuwen haalt de actuele serverregistraties opnieuw op");
Given("de vijf losse mailacceptatiescenario’s zijn vrijgegeven voor vaste testontvangers");
Then("kan Backoffice beide gecontroleerde PDF-bijlagen afzonderlijk openen vóór verzending");
When("de beheerder alleen de brokerbundel kiest en ontvanger en twee bijlagen bevestigt");
Then("bevat de write exact één scenario met expliciete bevestiging en geen bulkopdracht");
Given("mailroutering en aflevering is voorbereid");
When("de flow voor EQ-N-017 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat niet-beschikbare acceptatieconsole blijft volledig uit beeld");
Given("een goedgekeurde maar nog niet definitieve serverfactuur als Backoffice-taak klaarstaat");
When("Backoffice de verzending één keer afrondt");
Then("wordt eerst gelockt, niet te vroeg gequeued en verdwijnt de afgeronde vervolgtaak");
Given("de lokale status verouderd is maar de serveruren nog ingediend zijn");
When("de flow voor EQ-N-021 wordt uitgevoerd");
Then("verschijnt geen factuurverzendtaak en wordt geen lock-write uitgevoerd");
When("de flow voor EQ-N-019 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat gesloten acceptatievenster toont waarom geen mail kan worden verstuurd");
Given("het fail-closed retrybeleid voor acceptatiemail wordt uitgevoerd");
When("de flow voor EQ-N-018 wordt uitgevoerd");
Then("is een acceptatiefout single-shot en behoudt gewone mail begrensde retries");
Given("geen sessie");
When("GET email-queue zonder sessie");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker krijgt 401 op list");
Given("een ingelogde medewerker");
When("de medewerker de queue opvraagt");
Then("wordt met Playwright-assertions bevestigd dat medewerker krijgt 403 op list");
Given("een ingelogde admin");
When("enqueue wordt aangeroepen zonder invoice_id");
Then("wordt met Playwright-assertions bevestigd dat action=enqueue zonder invoice_id geeft 400");
When("enqueue wordt aangeroepen met niet-bestaand invoice_id");
Then("wordt met Playwright-assertions bevestigd dat action=enqueue niet-bestaande factuur geeft 404");
Given("een goedgekeurde-maar-niet-gelockte urenstaat");
When("enqueue wordt aangeroepen voor een factuur die nog niet gelockt is");
Then("wordt met Playwright-assertions bevestigd dat action=enqueue niet-gelockte factuur geeft 409");
Given("een queued (niet-failed) delivery item");
When("retry wordt aangeroepen op een queued item");
Then("wordt met Playwright-assertions bevestigd dat action=retry op queued item geeft 409");
When("status=invalid wordt meegestuurd");
Then("wordt met Playwright-assertions bevestigd dat ongeldige status-filter geeft 400");
When("POST email-queue zonder sessie");
Then("wordt met Playwright-assertions bevestigd dat anonieme enqueue geeft 401");
When("een onbekende action wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat unknown action geeft 400");
Given("de standaard testconfiguratie geen echte acceptatieverzending vrijgeeft");
When("een scenario zonder de exacte bevestiging wordt aangeboden");
Then("wordt met Playwright-assertions bevestigd dat acceptatieconsole blijft standaard uit en weigert POST zonder expliciete bevestiging");
When("de flow voor EQ-N-016 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat medewerker krijgt geen toegang tot de mailacceptatieconsole");
