// Navigation-only mapping for end-to-end-workflows.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/business-workflows-e2e.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("Backoffice de vaste herstelbasis met twaalf open acties opent");
When("Backoffice van augustus naar juli en terug naar augustus wisselt");
Then("blijven totaal, eigenaarschap en taakidentiteiten ongewijzigd");
And("de eigenaarfilters tonen uitsluitend hun zeven en vijf concrete acties");
Given("de TEST-login met accountkeuzes zichtbaar is");
When("Stasjo via de medewerkerskeuze wordt geselecteerd");
Then("staan zijn testcredentials direct klaar en is Herstel na inloggen verborgen");
When("naar Joyce als beheerder wordt gewisseld zonder pagina-herlaad");
Then("wisselen de credentials direct en krijgt Backoffice de herstelbediening");
Given("de herstelbasis Stasjo een correctieactie en Backoffice zeven acties geeft");
When("Stasjo zijn correctie opent en opnieuw indient");
Then("krijgt Backoffice direct de vervolgcontrole zonder verlies van het globale totaal");
Given("Backoffice een ingediende urenstaat uit de vaste herstelbasis opent");
When("Backoffice die urenstaat goedkeurt");
Then("verdwijnt alleen de urencontrole en verschijnt een factuuractie voor hetzelfde dossier");
Given("Backoffice een ontvangen klanturenstaat in de vaste herstelbasis heeft");
When("Backoffice het ontvangen klantdocument goedkeurt");
Then("staat hetzelfde dossier klaar voor de broker en blijft het globale totaal stabiel");
Given("een actieve medewerker een resetlink aanvraagt");
When("de medewerker via de link een sterk nieuw wachtwoord instelt");
Then("werkt het nieuwe wachtwoord en is dezelfde link niet opnieuw bruikbaar");
