// Navigation-only mapping for help-widget.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/help-widget.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../help-widget.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker opent Hulp & contact");
Then("verschijnt de eigen vraag en het juiste standaardantwoord met een knop naar Mijn uren");
When("de medewerker op de knop klikt");
Then("opent daadwerkelijk Mijn uren");
Given("de medewerker heeft binnen het gesprek een vraag gesteld");
When("de medewerker Gesprek wissen gebruikt");
Then("blijft alleen de begroeting over, met een melding dat het is gewist");
When("de medewerker opnieuw een vraag stelt en de pagina daarna echt herlaadt");
Then("is het gesprek net zo leeg als bij een eerste opening, niet ergens onthouden");
When("de medewerker het onderwerp Contact opnemen kiest");
Then("staat er precies één mailto-knop en één kopieerknop, geen los Gmail-alternatief");
Given("de schakelaar staat uit (standaard) en de medewerker vraagt naar verlof");
When("de beheerder verlof/ziekte handmatig invullen aanzet");
Then("krijgt de medewerker nu het antwoord dat wél naar de maandsamenvatting verwijst");
Given("de medewerker heeft geen voorkeur voor verminderde beweging ingesteld");
When("de medewerker Hulp & contact opent");
Then("krijgt het paneel de is-open-klasse en telt op als daadwerkelijk zichtbaar");
When("de medewerker het paneel sluit");
Then("verdwijnt het paneel weer volledig, ook na de sluitovergang");
Given("de medewerker heeft verminderde beweging ingesteld en het paneel staat open");
Then("is het paneel direct verborgen, niet pas na de normale overgangsduur");
