// Navigation-only mapping for invoices.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/invoices.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../invoices.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de administrator is ingelogd");
When("de administrator het facturenscherm opent");
Then("facturen per periode zijn zichtbaar zonder consolefouten");
Given("facturen bekijken en beheren is voorbereid");
When("de flow voor INV-H-013 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat documentarchief toont factuur en klanturenstaat zonder bestanden vooraf te laden");
When("de flow voor INV-N-014 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat ontbrekende klanturenstaat accepteert uitsluitend PDF JPG of PNG");
Given("Backoffice de door Shawn rechtstreeks gemailde urenstaat in september opent");
When("Backoffice de ontvangen urenbevestiging met een standaardreden vastlegt");
Then("telt de urenstaat groen mee en kan Backoffice de bevestiging terugdraaien");
Given("Stasjo goedgekeurde septemberuren heeft maar nog geen factuurrij");
When("Backoffice de controle afrondt");
Then("maakt de app de serverfactuur vanuit de goedgekeurde urenstaat en sluit de taak");
When("de flow voor INV-H-018 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat externe factuur slaat PDF JPG en PNG via de factuur-API op");
When("de flow voor INV-N-017 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat medewerker mag geen externe factuur uploaden");
When("de flow voor INV-H-016 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat factuurdataset met 32 records wordt in pagina’s van maximaal 25 getoond");
Given("de medewerker is ingelogd");
When("de medewerker factuurdata opvraagt");
Then("alleen eigen facturen zijn zichtbaar zonder consolefouten");
Given("de administrator is ingelogd en op het facturenscherm staat");
When("de administrator wisselt tussen juli en augustus 2026");
Then("het factuuroverzicht ververst voor de gekozen periode");
When("factuurdata voor augustus 2026 wordt opgevraagd");
Then("het bedrag komt uit server-side berekening in plaats van alleen statische demo-output");
Given("de administrator is ingelogd en op facturen staat");
When("de gekozen maanddetails worden verborgen en opnieuw getoond");
Then("blijven het overzicht en de gekozen maand netjes gescheiden zichtbaar");
Given("de administrator is ingelogd met de vaste demo-baseline");
When("de flow voor INV-H-007 wordt uitgevoerd");
Then("toont Facturen één oranje blokkadebadge en één groene controlebadge");
Given("Backoffice op TEST in september inlogt met vier nog niet ingediende urenstaten");
When("Backoffice de septemberfacturen opent");
Then("toont september vier blokkades en geen afgeronde maandcontrole");
Given("de administrator is ingelogd en reset naar vaste baseline");
When("de administrator een klaarstaande factuur via API opvraagt");
Then("is de invoice-data consistent (PDF format fix validates content structure)");
When("een ongeldige periodefilter wordt opgevraagd");
Then("geeft de API invalid-period met status 400 terug");
Given("de administrator is ingelogd met demo-data");
When("de app de gecontroleerde conceptfactuur voor verzending genereert");
Then("is dezelfde payload een volledige geldige PDF voor de mailbijlage");
Given("de administrator is ingelogd met demo-data inclusief geassigneerde taken");
When("de administrator factuurdata voor augustus opvraagt met details");
Then("bevat de server-PDF alle inhoudssecties: FACTUUR, Facturerende, Factuur aan, Project, uren/tarief, Betaling");
When("de administrator het factuurscherm opent en een factuur sluit");
Then("zit in de gegenereerde PDF alle content (recipient, project, uren, tarief, betaling)");
