// Navigation-only mapping for invoice-company-identity.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/invoice-company-identity.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("facturerende onderneming en handelsnaam is voorbereid");
When("de flow voor INV-ID-H-001 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat handelsnaam en juridische naam staan samen op de factuurpreview");
When("de flow voor INV-ID-H-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat alleen juridische naam is als factuurweergave te kiezen");
When("de flow voor INV-ID-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat factuuridentiteit wordt door settings API opgeslagen en via bootstrap herladen");
When("de flow voor INV-ID-N-004 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat settings API weigert een onbekende factuurweergave");
When("de flow voor INV-ID-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat instellingen tonen verkoopklare bedrijfsidentiteit en beveiligde verzendmodus");
