// Navigation-only mapping for invoice-locking.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/invoice-lock.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een medewerker een urenstaat heeft ingediend in een herhaalbare testperiode");
And("een administrator die urenstaat goedkeurt");
When("de administrator de factuur finaliseert met lock-actie");
Then("worden nummer bedragen en locked_at server-side vastgelegd en blijft client-manipulatie zonder effect");
And("de administrator kan de server-side gegenereerde factuur-PDF downloaden");
And("cleanup de administrator-sessie wordt afgesloten");
Given("een medewerker een urenstaat indient in een geïsoleerde testperiode");
And("Backoffice de uren goedkeurt en de factuur definitief maakt");
When("Backoffice de gefactureerde maand alsnog voor correctie probeert te openen");
Then("de definitieve factuur en urenstatus onveranderd blijven");
Given("er is geen actieve sessie");
When("een lock-actie zonder sessie wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker kan factuur niet locken");
Given("de medewerker is ingelogd");
When("de medewerker een lock-actie verstuurt");
And("cleanup de sessie wordt afgesloten");
Then("wordt met Playwright-assertions bevestigd dat medewerker mag factuur niet finaliseren");
Given("een ingediende maar niet-goedgekeurde urenstaat");
When("de administrator de factuur probeert te finaliseren");
Then("wordt met Playwright-assertions bevestigd dat niet-goedgekeurde urenstaat kan niet worden gelockt");
Given("een administrator met een approved urenstaat");
When("de eerste lock-oproep succesvol is");
Then("wordt een tweede lock-oproep geweigerd en ontstaat geen duplicaat");
Given("facturen definitief maken en vergrendelen is voorbereid");
When("de flow voor INV-N-012 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat gelijktijdige lock-requests leveren exact één winnaar");
Given("een administrator een factuur heeft gefinaliseerd");
When("een anonieme gebruiker de factuur-PDF probeert te downloaden");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker kan factuur-PDF niet downloaden");
