// Navigation-only mapping for invoices.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/invoices.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../invoices.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de administrator is ingelogd");
When("de administrator het facturenscherm opent");
Then("facturen per periode zijn zichtbaar zonder consolefouten");
Given("de medewerker is ingelogd");
When("de medewerker factuurdata opvraagt");
Then("alleen eigen facturen zijn zichtbaar zonder consolefouten");
Given("de administrator is ingelogd en op het facturenscherm staat");
When("de administrator wisselt tussen juli en augustus 2026");
Then("het factuuroverzicht ververst voor de gekozen periode");
When("factuurdata voor augustus 2026 wordt opgevraagd");
Then("het bedrag komt uit server-side berekening in plaats van alleen statische demo-output");
Given("de administrator is ingelogd en op facturen staat");
When("de gekozen maanddetails worden verborgen en opnieuw getoond");
Then("blijven het overzicht en de gekozen maand netjes gescheiden zichtbaar");
Given("de administrator is ingelogd met de vaste demo-baseline");
When("de flow voor INV-H-007 wordt uitgevoerd");
Then("toont Facturen één oranje blokkadebadge en één groene controlebadge");
When("een ongeldige periodefilter wordt opgevraagd");
Then("geeft de API invalid-period met status 400 terug");
