// Navigation-only mapping for klassiek-verkenning.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/klassiek-verkenning.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../klassiek-verkenning.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een medewerker in Klassiek");
And("is de maandkeuze op minstens de desktopbreedtes van Mijn uren echt gemeten");
When("de flow voor KLV-N-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat het maandkeuzepaneel valt op geen enkele breedte buiten het scherm");
Given("een medewerker op Mijn uren van een open maand");
And("de urenstaat staat al met een versie op de server");
When("de eerste invoer onderweg is en er intussen twee nieuwe invoeren volgen");
Then("slaagt elke opslag en staan alle drie de waarden daarna op de server");
