// Navigation-only mapping for klassiek-verkenning.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/klassiek-verkenning.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../klassiek-verkenning.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een medewerker in Klassiek");
And("is de maandkeuze op minstens de desktopbreedtes van Mijn uren echt gemeten");
When("de flow voor KLV-N-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat het maandkeuzepaneel valt op geen enkele breedte buiten het scherm");
Given("een medewerker in Klassiek met de testbalk in de menubalk");
When("de flow voor KLV-N-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat in de menubalk van de medewerker overlapt niets elkaar, op geen enkele desktopbreedte");
Given("een medewerker op Mijn uren met een urenstaat die al een serverversie heeft");
When("een opslag onderweg is, de pagina herlaadt en die opslag pas daarna aankomt");
And("de medewerker daarna gewoon verder invult");
Then("wordt die invoer zonder foutmelding opgeslagen en staat hij na nog een herlading op de server");
When("de flow voor KLV-N-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat op geen enkel medewerkerscherm valt inhoud buiten de rechterrand rond de breekpunten");
Given("een beheerder in Klassiek");
When("de flow voor KLV-N-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat op geen enkel beheerscherm valt inhoud buiten de rechterrand rond de breekpunten");
Given("een beheerder op het dashboard");
When("de beheerder de klanturenstaten opent vanaf het dashboard");
Then("staat er een paginatitel");
And("heeft ieder scherm in de app een eigen titel");
Given("een medewerker op Mijn uren van een open maand");
When("de medewerker 25 uur op een dag intypt");
Then("is het vak ongeldig, staat er een duidelijke melding en gaat er niets naar de server");
And("geldt 24,5 ook als te veel, maar 24 precies niet");
When("de medewerker Mijn uren opent");
Then("staat er op Mijn uren geen klanturenstaatlabel of -paneel");
And("staat het label wel op het Klanturenstaat-scherm");
Given("vondsten uit de monkey-verkenning op Klassiek is voorbereid");
When("de flow voor KLV-H-010 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat op TEST staat alleen Herstel bovenin; thema, vormgeving en versie staan in het profielmenu");
Given("licht en Klassiek: de knoppen zeggen Donker en Modern");
When("naar donker, then zegt de themaknop Licht");
When("naar Modern, then zegt de vormgevingsknop Klassiek");
And("terug naar Klassiek en licht: weer Modern en Donker");
Then("wordt met Playwright-assertions bevestigd dat de knoppen onder Testfuncties tonen waar je naartoe gaat, niet waar je bent");
When("de flow voor KLV-N-022 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de statuspillen naast de koppen in Instellingen blijven binnen hun kaart op smalle telefoons");
And("geldt dezelfde grens voor Ziekte");
When("de flow voor KLV-N-023 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat verlof en ziekte accepteren geen onmogelijk aantal uren en gaan dan niet naar de server");
Given("een beheerder op Instellingen met drie mailregels in de geschiedenis");
When("de flow voor KLV-N-011 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de mailgeschiedenis in Instellingen blijft binnen beeld, ook met lange regels en een herstelknop");
Given("alleen één week van de maand is nog leeg");
When("de medewerker in één dag van die week uren typt");
Then("telt alleen die dag mee: nog steeds geen Maand indienen, ook niet na herladen");
Given("alleen één week is nog leeg en Maand indienen is er niet");
When("de medewerker die lege week opslaat");
Then("staat Maand indienen er in de weekweergave, zonder de tekst dat hij onder Hele maand staat");
When("de medewerker in de laatste open week op Standaardweek vullen drukt");
Then("kan de maand worden ingediend op Mijn uren");
And("wijst de hoofdknop op Vandaag naar Maand indienen");
Given("een week met nog open werkdagen");
When("de medewerker één dag invult, dan telt het label één af");
Then("staat er Compleet zodra elke werkdag van de week is ingevuld");
Given("Mijn uren op telefoonbreedte: het knopje staat vlak boven de weekkeuze");
When("de medewerker erop tikt, dan staat Vandaag open");
And("op desktopbreedte, waar de menubalk Vandaag al toont, staat het knopje er niet");
Then("wordt met Playwright-assertions bevestigd dat op de telefoon brengt een klein knopje bij de weekkeuze je terug naar Vandaag");
When("de flow voor KLV-H-017 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de standaardweek gebruikt hele dagen van 9 of 8 uur en de vrije dag die Beheer instelt");
When("de flow voor KLV-H-018 wordt uitgevoerd");
Then("staan er lokaal/op TEST 20 updates met datum en tijdstip, nieuwste eerst");
And("staan er 5 per pagina met Vorige en Volgende, tot en met de laatste pagina");
And("staat geen naam of gevoelig gegeven in de teksten");
And("op de PROD-host is het blok weg");
When("de flow voor KLV-H-019 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat ingevulde uren op Mijn uren zijn leesbaar in licht en donker, op telefoon en desktop");
When("de flow voor KLV-H-020 wordt uitgevoerd");
Then("noemt de knop per stap de juiste handeling (beslistabel)");
And("heeft de knop dezelfde vorm als de andere hoofdknoppen, in licht en donker");
And("de urenstaat staat al met een versie op de server");
When("de eerste invoer onderweg is en er intussen twee nieuwe invoeren volgen");
Then("slaagt elke opslag en staan alle drie de waarden daarna op de server");
Given("de medewerker heeft de voorbeeldgegevens hersteld en staat op Mijn uren");
When("de medewerker uren invult en die op de server worden opgeslagen");
Then("is de server weer leidend: de resetvlag is weg");
And("na F5 leest de app de urenstaat van de server en synchroniseert verder invullen gewoon");
When("de medewerker toch iets invult");
Then("noemt de melding de reden die de server gaf");
