// Navigation-only mapping for klassiek-verkenning.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/klassiek-verkenning.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../klassiek-verkenning.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een medewerker in Klassiek");
And("is de maandkeuze op minstens de desktopbreedtes van Mijn uren echt gemeten");
When("de flow voor KLV-N-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat het maandkeuzepaneel valt op geen enkele breedte buiten het scherm");
Given("een medewerker in Klassiek met de testbalk in de menubalk");
When("de flow voor KLV-N-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat in de menubalk van de medewerker overlapt niets elkaar, op geen enkele desktopbreedte");
Given("een medewerker op Mijn uren met een urenstaat die al een serverversie heeft");
When("een opslag onderweg is, de pagina herlaadt en die opslag pas daarna aankomt");
And("de medewerker daarna gewoon verder invult");
Then("wordt die invoer zonder foutmelding opgeslagen en staat hij na nog een herlading op de server");
When("de flow voor KLV-N-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat op geen enkel medewerkerscherm valt inhoud buiten de rechterrand rond de breekpunten");
Given("een beheerder in Klassiek");
When("de flow voor KLV-N-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat op geen enkel beheerscherm valt inhoud buiten de rechterrand rond de breekpunten");
Given("een beheerder op het dashboard");
When("de beheerder de klanturenstaten opent vanaf het dashboard");
Then("staat er een paginatitel");
And("heeft ieder scherm in de app een eigen titel");
Given("een medewerker op Mijn uren van een open maand");
When("de medewerker 25 uur op een dag intypt");
Then("is het vak ongeldig, staat er een duidelijke melding en gaat er niets naar de server");
And("geldt 24,5 ook als te veel, maar 24 precies niet");
When("de medewerker Mijn uren opent");
Then("staat er op Mijn uren geen klanturenstaatlabel of -paneel");
And("staat het label wel op het Klanturenstaat-scherm");
Given("een medewerker in Klassiek op een telefoon van 390px");
Then("staat er één testpil in plaats van losse knoppen");
When("de medewerker de pil opent, then staan alle testknoppen voluit, 44px hoog en binnen beeld");
And("werkt een keuze in het paneel en gaat het paneel daarna dicht");
And("sluit Escape het paneel");
And("staat het versienummer onderaan het profielmenu");
And("blijft desktop ongewijzigd: geen pil, knoppen direct in de menubalk");
And("de urenstaat staat al met een versie op de server");
When("de eerste invoer onderweg is en er intussen twee nieuwe invoeren volgen");
Then("slaagt elke opslag en staan alle drie de waarden daarna op de server");
