// Navigation-only mapping for live-test-regression.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/../remote/*.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../../remote/*.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("live TEST-regressie en deployacceptatie is voorbereid");
When("de flow voor TEST-E2E-13 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat klanturenstaat-toestandsketen: indienen, opnieuw opvragen, herindienen, goedkeuren, brokerroute");
When("de flow voor TEST-E2E-15 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat uren-invoer EP/BVA: 0 en 24 door, negatief, >24 en niet-numeriek fail-closed");
When("de flow voor TEST-E2E-19 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat robuustheid: te lange invoer begrensd, dubbele acties idempotent, gelijktijdige writes consistent");
When("de flow voor TEST-E2E-21 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat exploratory: mededeling plaatsen, ontvangen, intrekken met historie; instellingenmenu compleet");
When("de flow voor TEST-E2E-34 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een mededeling met scriptinhoud belandt als tekst bij de medewerker, niet als code");
When("de flow voor TEST-E2E-22 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat herinneringen: samenvatting volgt exact de instellingen, klanturenstaat-tijd bereikt de server, voorbeeld zonder neveneffect");
When("de flow voor TEST-E2E-23 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat verse beheerder: aanmaken, inloggen, goedkeuren en factuur afronden");
When("de flow voor TEST-E2E-24 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat medewerker deactiveren blokkeert inloggen; data blijft; heractiveren herstelt toegang");
When("de flow voor TEST-E2E-27 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat goedgekeurde urenstaat zonder factuur mag terug naar correctie; met factuur wordt heropenen geweigerd");
When("de flow voor TEST-E2E-30 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat twee medewerkers met hetzelfde nummer-sjabloon in dezelfde periode krijgen elk een uniek nummer");
When("de flow voor TEST-E2E-31 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat marc en Brian: volledige afrond-flow levert de branded jsPDF-factuur");
When("de flow voor TEST-E2E-10 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat elke bestaande factuur heeft een echt nummer en geen CONCEPT-markering in de PDF");
When("de flow voor TEST-E2E-11 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat nieuwe medewerker via het beheer-scherm: volledige flow tot de jsPDF-conceptfactuur");
Given("twee Overig-ontvangers bij de medewerker, één met Factuur meesturen aan en één uit");
When("de volledige factuurketen via de GUI wordt afgerond");
Then("gaat de factuur mee naar de aangevinkte Overig-ontvanger en niet naar de uitgevinkte");
When("de flow voor TEST-E2E-12 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat urenstaat-toestandsketen: indienen, correctie, herindienen, goedkeuren; ongeldige overgang geweigerd");
When("de flow voor TEST-E2E-14 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat klanturenstaat-upload: geldige typen door, ongeldige fail-closed, concept ongewijzigd");
When("de flow voor TEST-E2E-16 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat rol-beslissingstabel: medewerker geweigerd op beheeracties, beheerder toegestaan");
When("de flow voor TEST-E2E-17 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat één factuuractie levert exact drie gescheiden routes met het juiste bijlagebeleid");
When("de flow voor TEST-E2E-18 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat negatieve controles: CSRF verplicht, XSS geëscaped, stale version geweigerd");
When("de flow voor TEST-E2E-20 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat werkvoorraad-invariant: alle acties = Backoffice + medewerkers, ongewijzigd bij maandnavigatie");
When("de flow voor TEST-E2E-06 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat elke demo-medewerker ziet alleen eigen data; alle facturen hebben een echt nummer");
When("de flow voor TEST-E2E-07 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat nieuwe medewerker met eigen opdracht-opties: volledige keten en eigen factuurnummer");
When("de flow voor TEST-E2E-08 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat herinneringen: instelling bewaren en een veilige voorbeeldmelding");
When("de flow voor TEST-E2E-28 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een medewerker komt niet bij de gegevens of acties van een andere medewerker");
When("de flow voor TEST-E2E-01 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat inloggen: juiste credentials binnen, foute geweigerd");
Given("een eerste resetaanvraag een eenmalige link geeft");
And("een tweede aanvraag een nieuwe link geeft");
When("de nieuwste link een nieuw wachtwoord zet");
Then("werkt het nieuwe wachtwoord");
And("zijn zowel het gebruikte als het vervangen token ongeldig");
When("de flow voor TEST-E2E-03 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat medewerker aanmaken, laat hem zelf inloggen en alleen eigen uren zien");
When("de flow voor TEST-E2E-04 wordt uitgevoerd");
Then("is de definitieve factuur de jsPDF-conceptfactuur zonder CONCEPT-markering");
And("toont de factuurpreview het juiste nummer, de IBAN en de bedragen");
And("klopt het mailverkeer: routering, onderwerpen, bijlagebeleid");
When("de flow voor TEST-E2E-05 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat acceptatieconsole verstuurt de vijf scenario-mails naar de sink");
When("de flow voor TEST-E2E-29 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een wachtwoord-vergeten-aanvraag wordt op de live SMTP-weg echt verstuurd");
When("de flow voor TEST-E2E-33 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de wachtwoord-reset-drempel stopt de vierde aanvraag binnen het venster");
When("de flow voor TEST-SMOKE-01 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de TEST-site draait de verwachte versie met veilige headers");
When("de flow voor TEST-E2E-26 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de deploy levert de veiligheidsheaders en PWA-assets die de app nodig heeft");
When("de flow voor TEST-E2E-32 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de live sessie is een veilige cookie en valt na uitloggen echt om");
When("de flow voor TEST-SMOKE-02 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat beheerder kan inloggen en elke view laadt zonder fouten");
When("de flow voor TEST-SMOKE-03 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat medewerker ziet alleen de eigen uren");
When("de flow voor TEST-SMOKE-04 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de factuurpreview rendert met bedragen en bedrijfsidentiteit");
