// Navigation-only mapping for mobile.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/mobile-ui.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../mobile-ui.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de mobiele loginpagina");
When("een administrator inlogt en door de mobiele navigatie gaat");
Then("Home en rolwissel blijven bereikbaar zonder console- of page-errors");
Given("een medewerker met een mobiele schrijfbare maand");
When("uren als concept worden gewijzigd en daarna ingediend");
Then("klanturenstaat en notificaties blijven mobiel bereikbaar");
Given("de medewerker mobiel uren indient");
When("de administrator mobiel een correctie vraagt");
Then("de medewerker de melding leest aanpast en opnieuw indient");
And("de administrator mobiel goedkeurt");
Given("een administrator in het mobiele factuuroverzicht");
When("de flow voor MOB-N-004 wordt uitgevoerd");
Then("de brede factuurtabel als mobiele kaartweergave rendert");
And("touch controls en bevestigingsmodal binnen viewport blijven");
Given("een beheerder de mobiele Instellingen opent");
When("de flow voor MOB-H-005 wordt uitgevoerd");
Then("de verzendregistratie als leesbare kaart binnen het scherm staat");
And("geheime inhoud verborgen blijft en Vernieuwen een touchdoel is");
And("de losse mailacceptatieactie binnen het scherm blijft met een volwaardig touchdoel");
