// Navigation-only mapping for notifications.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/notifications.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een ingelogde medewerker");
When("notificaties worden opgehaald");
Then("wordt met Playwright-assertions bevestigd dat ingelogde gebruiker kan notificaties ophalen");
Given("een ingelogde admin");
When("mark_all_read wordt aangeroepen");
Then("wordt met Playwright-assertions bevestigd dat mark_all_read werkt zonder fouten");
Given("meldingen en notificaties is voorbereid");
When("notificaties.php zonder sessie wordt aangeroepen");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker krijgt 401 op notificaties");
When("een onbekende action wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat unknown action geeft 400");
When("de flow voor NOT-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat notificatielimiet wordt op minimaal een begrensd");
When("de flow voor NOT-H-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat unread-filter retourneert uitsluitend ongelezen meldingen");
When("de flow voor NOT-N-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat mark_read zonder notification_id geeft 400");
When("de flow voor NOT-H-008 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat mark_read voor onbekende melding wijzigt nul records");
