// Navigation-only mapping for notifications.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/notifications.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../notifications.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een ingelogde medewerker");
When("notificaties worden opgehaald");
Then("wordt met Playwright-assertions bevestigd dat ingelogde gebruiker kan notificaties ophalen");
Given("een ingelogde admin");
When("mark_all_read wordt aangeroepen");
Then("wordt met Playwright-assertions bevestigd dat mark_all_read werkt zonder fouten");
Given("meldingen beheren is voorbereid");
When("notificaties.php zonder sessie wordt aangeroepen");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker krijgt 401 op notificaties");
When("een onbekende action wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat unknown action geeft 400");
When("de flow voor NOT-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat notificatielimiet wordt op minimaal een begrensd");
When("de flow voor NOT-H-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat unread-filter retourneert uitsluitend ongelezen meldingen");
When("de flow voor NOT-N-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat mark_read zonder notification_id geeft 400");
When("de flow voor NOT-H-008 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat mark_read voor onbekende melding wijzigt nul records");
When("de flow voor NOT-H-009 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat alles gelezen wist teller en een oudere response kan deze niet herstellen");
When("de flow voor NOT-H-010 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat herstel zet drie lokale basismeldingen terug en beschermt ze tegen serveroverschrijving");
Given("drie ongelezen mededelingen en een ongelezen statusmelding");
Then("staat alleen de statusmelding in de bel");
And("staan in Berichten de ongelezen open en bovenaan, de gelezen ingeklapt, zonder markeerknop");
When("elk ongelezen bericht 2 seconden in beeld is, then telt het vanzelf als gelezen");
And("blijven de net gelezen berichten open staan; na herladen zijn ze ingeklapt");
When("de flow voor NOT-N-015 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een ongelezen bericht dat maar kort in beeld is, blijft ongelezen");
Given("Stasjo opent Berichten met ingetrokken voorbeeldmededelingen in de TEST-basis");
When("hij het filter Ingetrokken kiest");
Then("staan alleen ingetrokken berichten er, ingeklapt met label, en geen ervan als ongelezen");
And("zie je de reden zodra je het bericht openklapt");
And("staat onder Alles een geldige mededeling niet als ingetrokken");
When("de flow voor NOT-H-013 wordt uitgevoerd");
Then("toont de bel alleen de drie meldingen over de medewerker zelf");
Given("twee ongelezen mededelingen in Berichten en één statusmelding in de bel");
When("de medewerker in Berichten op Alles gelezen tikt");
Then("zijn de mededelingen gelezen en blijft de statusmelding in de bel ongelezen");
