// Navigation-only mapping for password-reset.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/password-reset.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een geldig e-mailadres van een actieve gebruiker");
When("request-reset wordt aangeroepen");
Then("kan het token worden gebruikt om wachtwoord te resetten");
Given("een niet-bestaand e-mailadres");
Then("wordt met Playwright-assertions bevestigd dat onbekend e-mailadres retourneert ook ok=true (geen email-enumeration)");
Given("een ingelogde admin");
When("de flow voor PWD-H-003 wordt uitgevoerd");
Then("bevat me.php het force_password_change veld");
Given("een ingelogde beheerder");
When("het huidige en een sterk nieuw wachtwoord worden verstuurd");
Then("kan het wachtwoord via dezelfde beveiligde flow worden teruggezet");
Given("een resetlink voor een actieve medewerker is aangemaakt");
When("de medewerker de link opent en tweemaal hetzelfde sterke wachtwoord invult");
Then("is het wachtwoord gewijzigd en kan dezelfde link niet opnieuw worden gebruikt");
Given("een syntactisch geldige eenmalige resetlink is geopend");
When("twee verschillende sterke wachtwoorden worden ingevuld");
Then("blijft de gebruiker op het formulier met een duidelijke validatiemelding");
Given("wachtwoordherstel en misbruikbeveiliging is voorbereid");
When("de flow voor PWD-N-011 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat elf tekens ligt onder de wachtwoordgrens van twaalf");
When("reset-password wordt aangeroepen met neptoken");
Then("wordt met Playwright-assertions bevestigd dat reset-password met ongeldig token geeft 400");
Given("een geldig reset-token");
When("reset-password wordt aangeroepen met een wachtwoord onder twaalf tekens");
Then("wordt met Playwright-assertions bevestigd dat reset-password onder twaalf tekens geeft 400");
Given("een geldig token dat al gebruikt is");
When("hetzelfde token nogmaals wordt gebruikt");
Then("wordt met Playwright-assertions bevestigd dat hergebruik van al-gebruikt token geeft 409");
Given("een account met 5+ mislukte loginpogingen");
When("de flow voor PWD-N-007 wordt uitgevoerd");
Then("wordt de 6e poging geblokkeerd met 429");
When("de flow voor PWD-N-008 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat request-reset weigert GET");
When("de flow voor PWD-N-009 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat request-reset met leeg e-mailadres geeft 400");
