// Navigation-only mapping for period-management.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/period-management.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../period-management.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een ingelogde admin");
When("de periodes worden opgehaald");
Then("wordt met Playwright-assertions bevestigd dat admin kan periodes ophalen met overzicht");
When("de testperiode wordt gesloten");
Then("is de periode gesloten");
And("heropenen werkt");
Given("maandperiodes beheren is voorbereid");
When("periods.php wordt aangeroepen zonder sessie");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker krijgt 401 op periods");
Given("een ingelogde medewerker");
When("periods.php wordt aangeroepen als medewerker");
Then("wordt met Playwright-assertions bevestigd dat medewerker mag geen periodes beheren");
Given("een reeds gesloten periode");
When("dezelfde periode nogmaals wordt gesloten");
Then("wordt met Playwright-assertions bevestigd dat dubbel sluiten van periode geeft 409");
Given("een open periode en ingelogde admin");
When("een open periode wordt heropend");
Then("wordt met Playwright-assertions bevestigd dat heropenen van open periode geeft 409");
When("de flow voor PER-N-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat driecijferig jaar geeft 400");
When("de flow voor PER-N-008 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat vijfcijferig jaar geeft 400");
When("de flow voor PER-N-009 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat ongeldige maand geeft 400");
When("de flow voor PER-N-010 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat onbekende periodeactie geeft 400");
