// Navigation-only mapping for pilot-page.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/pilot-page.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../pilot-page.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de webroot met de app op /");
When("de medewerker- en Backoffice-pilot als eigen URL worden opgevraagd");
Then("dragen ze de pilot-vlag/marker en delen ze geen code met de app");
And("de bestaande app blijft er onaangeroerd naast draaien");
Given("de medewerker-pilot");
When("de pagina is geladen");
Then("staat september met week 36 klaar om in te vullen en de wekenmeter op nul");
Given("de medewerker-pilot met september open");
When("een lege dag wordt ingevuld, bijgesteld en de week wordt ingediend");
Then("springt de pilot naar week 37, die weer invulbaar is, en telt de meter mee");
When("met het pijltje een maand terug wordt gebladerd naar augustus");
Then("staan alle weken vast en toont de klanturenstaat het verzonden-vinkje");
When("een lege dag via de snelkeuze op 8 wordt gezet en de week wordt opgeslagen");
Then("bevestigt de pilot het opslaan maar blijft de week bewerkbaar en niet ingediend");
Given("de Backoffice-pilot met Shawn geselecteerd");
When("de rij van Marc de Roon wordt aangeklikt");
Then("verspringt de markering en toont het verhaalpaneel het verhaal van Marc");
Given("de statische Backoffice-pilot");
Then("staan de mockup-onderdelen in beeld met de vaste mockup-data");
Given("de Backoffice-pilot");
When("de wachtrij wordt getoond");
Then("is precies één rij gemarkeerd zonder verticale groene balk, met opgelichte horizontale proceslijn");
Given("de Backoffice-pilot met een geselecteerde medewerker");
When("het verhaalpaneel wordt getoond");
Then("dragen de kaarten de mockup-status en staat de vervolgknop klaar");
When("medewerker- en Backoffice-pilot naast elkaar worden bekeken");
Then("heeft de medewerker geen Backoffice-pijplijn en is de Backoffice-pilot als zodanig gemarkeerd");
Given("een telefoonviewport");
When("beide pilots worden geopend");
Then("past alles binnen de breedte en zijn tapdoelen minimaal 42px");
