// Navigation-only mapping for pilot-page.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/pilot-page.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../pilot-page.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("functionele 1919-pilotportals naast de bestaande app is voorbereid");
When("de flow voor PILOT-H-001 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat beide 1919-portals leven naast de bestaande app");
When("de flow voor PILOT-H-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat medewerker schrijft uren via dezelfde API en draagt de maand over");
When("de flow voor PILOT-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat rechtstreeks gemaild blijft oranje tot Backoffice extern bevestigt");
When("de flow voor PILOT-H-004 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat pDF-aanlevering komt bij Backoffice ter controle en kan worden goedgekeurd");
When("de flow voor PILOT-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat backoffice-correctie maakt de ingediende maand weer bewerkbaar");
When("de flow voor PILOT-H-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat maandkeuze blijft in de sessie en uitloggen herstelt de actuele maand");
When("de flow voor PILOT-N-001 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat rollen blijven ook op de pilot-URLs strikt gescheiden");
When("de flow voor PILOT-N-002 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat beide pilots blijven bedienbaar zonder horizontale overflow op telefoon");
