// Navigation-only mapping for pipeline-demo.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/pipeline-demo.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../pipeline-demo.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de zelfstandige TEST-only pipelinepagina met de echte projectstand");
When("de pagina is geladen, staan de vier fasen en de laatste vijf echte opleveringen op het bord");
And("Kennisbank en Testbeheer projecteren dezelfde echte cases en de Living Doc toont hooguit tien");
Then("wordt met Playwright-assertions bevestigd dat de demo toont de echte laatste opleveringen uit GIO-WENSEN met hun cases en Gherkin");
Given("een nieuwe wens met acceptatiecriterium");
When("de wens wordt doorgezet naar VS Code");
Then("staat de wens op het bord als wachtend op VS Code, ook na herladen");
And("een simulatie op dezelfde kaart loopt door vier fasen naar Zephyr en de Living Doc");
Given("de pipelinepagina met de echte projectstand");
When("er wordt gezocht, gefilterd, gesorteerd en een kaart wordt geopend");
Then("tonen bord, kennisbank en testbeheer telkens de bijbehorende selectie");
Given("de Kennisbank van de pipelinepagina");
When("de flow voor PIPE-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de Kennisbank leest in de Atlassian-letterstapel op 16px met regelhoogte 24px, licht en donker");
Given("een bezoeker met een donkere systeeminstelling");
When("de weergaveknop wordt gebruikt");
Then("blijft de keuze staan na herladen");
Given("interactieve Path Pipeline als zelfstandige TEST-demo met echte projectstand is voorbereid");
When("de Kennisbank op de telefoon wordt geopend");
Then("toont de Living Doc precies tien regels, lokaal vóór echt, en bewaart hij er tien");
And("de pagina heeft geen horizontale overflow of gedeelde appcode");
