// Navigation-only mapping for pipeline-demo.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/pipeline-demo.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../pipeline-demo.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de zelfstandige TEST-only pipelinepagina");
When("de pagina is geladen, staan de vier afgesproken fasen en vijf vaste tickets klaar");
And("Kennisbank en Testbeheer projecteren dezelfde traceerbare inhoud");
Then("wordt met Playwright-assertions bevestigd dat de demo verbindt backlog, kennisbank en testbeheer met vijf echte opleveringen");
Given("een nieuwe vraag met acceptatiecriterium");
When("de volledige pipeline automatisch wordt uitgevoerd");
Then("komt de testcase in Zephyr en de oplevering in de begrensde Living Doc");
Given("interactieve Path Pipeline als zelfstandige TEST-demo is voorbereid");
When("de Kennisbank op de telefoon wordt geopend");
Then("worden alleen de laatste vijf lokale regels getoond en tien lokaal bewaard");
And("de pagina heeft geen horizontale overflow of gedeelde appcode");
