// Navigation-only mapping for pipeline-demo.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/pipeline-demo.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../pipeline-demo.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("interactieve Path Pipeline als zelfstandige TEST-demo met echte projectstand is voorbereid");
When("de flow voor PIPE-N-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de oude bestandsnaam wijst door naar Path Kwaliteitsstraat, en de bestemming laadt zijn eigen stylesheet en script echt");
Given("de zelfstandige TEST-only pipelinepagina met de echte projectstand");
When("de pagina is geladen, staan de vier fasen en de eerste echte opleveringen op het bord");
And("de zoekbalk vindt ook een oplevering die buiten de eerste lading valt");
And("Kennisbank en Testbeheer projecteren dezelfde echte cases, met paginering in plaats van een afkap");
Then("wordt met Playwright-assertions bevestigd dat de demo toont de echte laatste opleveringen uit GIO-WENSEN met hun cases en Gherkin");
Given("de pagina opent in Confluence, want daar begint de keten");
And("vanaf het Jira-bord wijst een knop terug naar het loket");
And("een nieuwe wens met acceptatiecriterium");
When("de flow wordt gestart, gaat de wens naar de eigen wachtrij en niet naar GitHub");
Then("meldt de pagina dat hij is aangenomen en staat hij op het bord, ook na herladen");
And("een tweede bezoeker met een schone browser ziet dezelfde wens, want de wachtrij staat op de server");
And("een simulatie op dezelfde kaart loopt door vier fasen naar Zephyr en de Living Doc");
Given("een opgeleverd ticket wordt geopend vanaf het bord");
When("de flow voor PIPE-H-010 wordt uitgevoerd");
Then("staan de vaste blokken van een Jira-issuepagina er");
And("toont Traceability de echte testcases met techniek en assertions");
And("staan FO, TO en het databasemodel bij de story");
And("vertelt de historie wat er echt is gebeurd");
And("zijn de blokken in te klappen zoals in Jira");
Given("de opslag kent deze kaart nog niet");
When("de kaart naar In uitvoering wordt gesleept");
Then("weet de server het, met een geschiedenisregel erbij");
And("blijft hij daar na herladen, ook zonder de browseropslag");
And("een tweede lezer ziet dezelfde stand");
And("de kaart gaat terug, zodat deze case geen sporen achterlaat");
When("de flow voor PIPE-H-012 wordt uitgevoerd");
Then("claimt de pagina geen gereedschap dat we niet gebruiken");
And("stuurt geen enkele knop of link de lezer nog naar GitHub");
And("staan in het ticket de verwijzingen met hun echte nummer");
And("is de link naar dit ticket deelbaar");
And("wijst de keten door naar de uitkomst in de Living Doc");
And("brengt de Confluence-verwijzing je naar de pagina van hetzelfde nummer");
Given("het tabblad Releases");
When("de flow voor PIPE-H-011 wordt uitgevoerd");
Then("staat de nieuwste versie bovenaan met haar echte aantallen");
And("scheidt het filter gereleaste versies van wat nog op een versie wacht");
And("brengt klikken op een versie je naar precies die opleveringen");
Given("het koppelingen-endpoint van de open demo-omgeving");
When("de flow voor PIPE-H-009 wordt uitgevoerd");
Then("geldt onze eigen bron en staan de drie klantbronnen klaar");
And("staat er nergens een instelling in het antwoord");
And("legt de Kennisbank uit wat er per koppeling nodig is");
Given("de intakewachtrij van de open demo-omgeving");
When("er onvolledige, onleesbare, te grote en verkeerd geadresseerde verzoeken binnenkomen");
Then("staat er van al die pogingen niets in de wachtrij en lekt er geen IP-kenmerk");
And("op een productieomgeving bestaat de wachtrij helemaal niet");
Given("de keuzelijst toont de nice-to-haves uit GIO-WENSEN");
When("de PO een verbetering kiest, then staan samenvatting en waarde ingevuld en blijft het criterium aan hem");
And("zelf typen blijft mogelijk: aanpassen maakt de keuze niet ongedaan, loslaten wel");
And("het type heet Onderhoud, niet Chore");
And("de volgorde in Te doen is met het toetsenbord te wijzigen en blijft na herladen");
And("bovenin staat hoe vers de stand is en de versie staat in de voet zoals in de urenapp");
Then("wordt met Playwright-assertions bevestigd dat de keuzelijst vult het formulier voor, Te doen laat zich ordenen en de versie staat in de voet");
Given("Samenvatting en Gewenste waarde nog leeg zijn, then vraagt de knop erom in te vullen");
When("beide velden gevuld zijn en op voorstellen wordt geklikt, then komt er een testbaar criterium");
And("blijft het voorstel aanpasbaar: zelf typen overschrijft het gewoon");
And("geeft een getal in het criterium een concreet Then over dat getal");
And("geeft een bekend statuswoord een concreet Then over die status");
And("gaat er voor dit alles geen enkel verzoek naar een externe dienst");
Then("wordt met Playwright-assertions bevestigd dat het loket stelt zelf een testbaar acceptatiecriterium voor, zonder externe aanroep");
Given("1200px (net onder de drempel): de lay-out is gestapeld en breed genoeg om te lezen");
When("de viewport 1px breder wordt (1201px), then komt de zijbalk terug zonder de kolom kapot te knijpen");
And("op 1280px, de standaard testbreedte van deze hele suite, blijft de zijbalk zichtbaar en de kolom leesbaar");
And("ook op een gewoon breed bureaubladscherm (1600px) is de kolom nog steeds leesbaar breed");
Then("wordt met Playwright-assertions bevestigd dat tussen de mobiele en de bureaubladdrempel blijft de Confluence-kolom leesbaar breed");
Given("de pipelinepagina met de echte projectstand");
When("er wordt gezocht, gefilterd, gesorteerd en een kaart wordt geopend");
Then("tonen bord, kennisbank en testbeheer telkens de bijbehorende selectie");
Given("de Kennisbank van de pipelinepagina");
When("de flow voor PIPE-H-003 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de Kennisbank leest in de Atlassian-letterstapel op 16px met regelhoogte 24px, licht en donker");
Given("een bezoeker met een donkere systeeminstelling");
When("de weergaveknop wordt gebruikt");
Then("blijft de keuze staan na herladen");
When("de Kennisbank op de telefoon wordt geopend");
Then("tekent de Living Doc tien regels per keer, lokaal vóór echt, en bewaart hij er hooguit 25");
And("de pagina heeft geen horizontale overflow of gedeelde appcode");
Given("de Living Doc in de Kennisbank");
When("de flow voor PIPE-H-006 wordt uitgevoerd");
Then("blijft de regel ook op een telefoon binnen beeld");
