// Navigation-only mapping for production-safety.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/production-safety.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de lokale login-hints worden gecontroleerd");
When("de gebruiker de admin-loginkeuze opent");
Then("wordt alleen in lokale hintmodus een demo-wachtwoord voorgeselecteerd");
Given("de frontend source wordt opgehaald");
When("de flow voor SAFE-N-001 wordt uitgevoerd");
Then("bevat de frontend geen plaintext demo-credentials");
Given("een ingelogde medewerker");
When("een write-call zonder csrf-header wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat writes zonder csrf blijven geblokkeerd");
Given("een ingelogde medewerker met schrijfbare periode");
When("de medewerker save_draft uitvoert");
Then("submit met expected_version blijft werkend");
Given("de productieconfig-templatebestanden worden ingelezen");
When("de flow voor SAFE-N-003 wordt uitgevoerd");
Then("staan demo-migraties standaard uit in productieconfig");
Given("de health.php broncode wordt gelezen");
When("de flow voor SAFE-H-003 wordt uitgevoerd");
Then("bevat health.php een productieguard die host en databasenaam wegfiltert");
Given("install.php en migrate.php worden gelezen");
When("de flow voor SAFE-N-004 wordt uitgevoerd");
Then("bevatten beide bestanden een HTTP-blokkering voor productieomgeving");
Given("config.example.php wordt gelezen");
When("de flow voor SAFE-H-004 wordt uitgevoerd");
Then("staat mail.enabled standaard op false en is SMTP relay voorbereid zonder activering");
Given("de loginpagina als productiepresentatie wordt opgebouwd");
When("de flow voor SAFE-N-005 wordt uitgevoerd");
Then("zijn demoaccounts en lokale uitleg niet zichtbaar");
And("zonder authservice blijft productie fail-closed");
Given("de Playwright-bootstrap en directe DB-smoke worden gecontroleerd");
When("de flow voor SAFE-N-006 wordt uitgevoerd");
Then("vereist de bootstrap een herkenbare testdatabase of geïsoleerde lokale CI-database");
And("gebruikt de CRUD-smoke dezelfde fail-closed scheiding");
Given("de CLI-only productieconfigurator wordt gelezen");
When("de flow voor SAFE-N-007 wordt uitgevoerd");
Then("vereist configuratie expliciete uitvoering, bevestiging en verborgen invoer");
And("valideert hij DB en private storage vóór een atomische 0600-write met mail uit");
Given("de transport-, dispatch- en productiepreflightbron wordt gelezen");
When("de flow voor SAFE-H-005 wordt uitgevoerd");
Then("zijn TLS, dry-run, private storage, HSTS en niet-mutatieve checks afgedwongen");
Given("de CLI-only productiebedrijfs-bootstrap wordt gelezen");
When("de flow voor SAFE-H-006 wordt uitgevoerd");
Then("vereist de bootstrap productie, expliciete bevestiging en geldige bedrijfsgegevens");
And("maakt hij alleen een lege database aan, logt de handeling en overschrijft nooit afwijkende data");
