// Navigation-only mapping for reminders.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/reminders.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../reminders.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de wekelijkse herinnering staat aan voor nu (vandaag, huidige tijd, Europe/Amsterdam)");
When("de scheduler voor het eerst draait");
Then("staat er een reminder-mail in de queue voor de nieuwe medewerker");
And("een tweede run binnen dezelfde week verstuurt niets extra (idempotent)");
And("cleanup");
