// Navigation-only mapping for roles-api.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/roles-api.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("er is geen actieve sessie");
When("bootstrap dashboard en invoices anoniem worden opgevraagd");
Then("wordt met Playwright-assertions bevestigd dat zonder sessie geeft protected API 401");
Given("de administrator is ingelogd");
When("de administrator bootstrapdata opvraagt");
And("de administrator dashboarddata opvraagt");
Then("de administrator ziet volledige invoice-data");
Given("de medewerker is ingelogd");
When("de medewerker bootstrapdata opvraagt");
Then("de medewerker ziet alleen eigen invoice-data");
