// Navigation-only mapping for security.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/security.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("er is geen bestaande sessie nodig voor csrf-opvraag");
When("de client een csrf-token opvraagt");
Then("ontvangt de client een geldige csrf-token payload");
Given("geldige administrator-inloggegevens beschikbaar zijn");
When("de administrator inlogt met csrf-bescherming");
Then("ontstaat een geldige administrator-sessie");
Given("een ingelogde administrator-sessie");
When("de gebruiker uitlogt met csrf-token");
Then("wordt de sessie netjes afgesloten");
Given("een loginpoging zonder csrf-header");
When("login zonder csrf wordt verstuurd");
Then("geeft de server csrf-invalid met status 403 terug");
Given("een logoutpoging zonder csrf-header");
When("logout zonder csrf wordt verstuurd");
Given("een geldige csrf-token met ongeldige loginpayload");
When("de flow voor SEC-N-003 wordt uitgevoerd");
Then("geeft de server invalid-payload met status 400 terug");
Given("er is geen actieve sessie");
When("protected read-endpoints worden opgevraagd");
Then("wordt met Playwright-assertions bevestigd dat zonder sessie protected API blijft 401");
Given("authenticatie- en API-beveiliging is voorbereid");
When("de flow voor SEC-H-004 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat csrf-token blijft stabiel binnen dezelfde sessie");
When("de flow voor SEC-N-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat csrf-endpoint weigert POST");
When("de flow voor SEC-N-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat login-endpoint weigert GET");
When("de flow voor SEC-N-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat logout-endpoint weigert GET");
When("de flow voor SEC-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat sessiecode bevat expliciete timeout-check en sliding expiration");
When("de flow voor SEC-H-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat herhaalde mislukte loginpogingen maken security-audit event");
When("de flow voor SEC-H-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat config voorbeeld bevat voorbereide CSP/CORS/HSTS flags");
