// Navigation-only mapping for security.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/security.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../security.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("er is geen bestaande sessie nodig voor csrf-opvraag");
When("de client een csrf-token opvraagt");
Then("ontvangt de client een geldige csrf-token payload");
Given("geldige administrator-inloggegevens beschikbaar zijn");
When("de administrator inlogt met csrf-bescherming");
Then("ontstaat een geldige administrator-sessie");
Given("een ingelogde administrator-sessie");
When("de gebruiker uitlogt met csrf-token");
Then("wordt de sessie netjes afgesloten");
Given("een loginpoging zonder csrf-header");
When("login zonder csrf wordt verstuurd");
Then("geeft de server csrf-invalid met status 403 terug");
Given("een logoutpoging zonder csrf-header");
When("logout zonder csrf wordt verstuurd");
Given("een geldige csrf-token met ongeldige loginpayload");
When("de flow voor SEC-N-003 wordt uitgevoerd");
Then("geeft de server invalid-payload met status 400 terug");
Given("er is geen actieve sessie");
When("protected read-endpoints worden opgevraagd");
Then("wordt met Playwright-assertions bevestigd dat zonder sessie protected API blijft 401");
Given("authenticatie- en API-beveiliging is voorbereid");
When("de flow voor SEC-H-004 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat csrf-token blijft stabiel binnen dezelfde sessie");
When("de flow voor SEC-N-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat csrf-endpoint weigert POST");
When("de flow voor SEC-N-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat login-endpoint weigert GET");
When("de flow voor SEC-N-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat logout-endpoint weigert GET");
When("de flow voor SEC-H-005 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat sessiecode bevat expliciete timeout-check en sliding expiration");
When("de flow voor SEC-H-006 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat herhaalde mislukte loginpogingen maken security-audit event");
Given("een geseed medewerkersaccount dat nergens anders mislukte pogingen krijgt");
When("er twee keer mislukt wordt ingelogd (net onder de drempel)");
Then("bestaat er nog geen drempel-event (de grens ligt bij drie, niet twee)");
When("een derde mislukte poging de drempel haalt");
Then("verschijnt precies één event, met het juiste account en de juiste inhoud");
When("nog een mislukte poging volgt binnen hetzelfde venster (blijft ruim onder de eigen inlogdrempel van vijf, zie AUTH-N-008/PWD-N-018 -- dit account wordt hierna door andere cases nog echt gebruikt om in te loggen)");
Then("blijft het nog steeds precies één event: de dedup-guard voorkomt een tweede");
When("de flow voor SEC-H-007 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat config voorbeeld bevat voorbereide CSP/CORS/HSTS flags");
Given("een willekeurig, niet-geauthenticeerd endpoint");
When("de client dat endpoint bevraagt");
Then("staan de vaste beveiligingsheaders echt op het antwoord");
Given("een verzoek met een toegestane origin uit de lokale/test-allowlist");
Then("weerspiegelt de server precies die origin met credentials toegestaan");
When("hetzelfde verzoek een niet-vertrouwde origin meestuurt");
Then("geeft de server geen Access-Control-Allow-Origin voor die origin terug");
Given("een ingelogde medewerker op het eigen dashboard");
When("de hash handmatig naar een beheerder-only scherm wordt gezet");
Then("blijft de medewerker op het eigen dashboard, niet op Instellingen");
Given("een ingelogde medewerker");
When("de pagina wordt herladen met een beheer-only hash al in de URL (bv. bewaarde link)");
Then("start de medewerker alsnog op het eigen dashboard, niet op Medewerkersbeheer");
When("de hash handmatig naar het beheer-klanturenstatenscherm wordt gezet");
Then("blijft de medewerker op het eigen dashboard, met de bijbehorende hash en titel");
When("de bewaarde staat handmatig op de beheerdersrol wordt gezet");
Then("start de app na herladen gewoon als medewerker");
Given("het publiek opgehaalde assets/app.js");
When("de flow voor SEC-H-014 wordt uitgevoerd");
Then("bevat het geen van de echte tarieven, contractvormen of bemiddelaargegevens");
And("staat de scheiding zelf overeind: app.js verwijst naar het aparte seed-bestand, kent het niet uit het hoofd");
When("de flow voor SEC-N-009 wordt uitgevoerd");
Then("werkt een normale login daarna nog gewoon (de tabel bestaat nog, niets is gecorrumpeerd)");
When("de flow voor SEC-N-010 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een padtraversalpoging op een periode-parameter wordt afgewezen, niet stilzwijgend genegeerd tot een ander antwoord");
When("de flow voor SEC-H-015 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat de sessiecookie draagt HttpOnly en SameSite=Lax");
When("de flow voor SEC-N-011 wordt uitgevoerd");
Then("wordt met Playwright-assertions bevestigd dat een kapotte JSON-payload lekt geen bestandspad of stacktrace naar de client");
