// Navigation-only mapping for skin.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/skin.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../skin.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een verse browser op de loginpagina");
When("er nog geen vormgeving is gekozen");
Then("blijft de app ook na inloggen in de klassieke vormgeving");
Given("een ingelogde administrator");
When("de flow voor SKIN-H-002 wordt uitgevoerd");
Then("draait de app door in de nieuwe skin en overleeft die een herlading");
Given("de app staat in de nieuwe skin");
When("de flow voor SKIN-H-003 wordt uitgevoerd");
Then("is de klassieke vormgeving terug, ook na herladen");
Given("een ingelogde administrator in de klassieke vormgeving");
When("de gebruiker de nieuwe vormgeving activeert");
Then("zijn de 1414/1919-tokens en lokale serif alleen daar actief");
Given("een ingelogde administrator met de standaardvoorkeuren");
When("Nieuw voor het eerst direct wordt geopend");
Then("bewaart iedere skin zijn eigen keuze bij heen en weer schakelen");
Given("de medewerker de nieuwe vormgeving opent");
When("het echte dashboard de bento met live invoervelden en gezamenlijke versie-footer tekent");
And("eerdere weken niet indienen en de laatste week eerst bevestiging vraagt");
Then("blijven op telefoon weekinvoer, klanturenstaat en stappen binnen het scherm");
Given("Backoffice is ingelogd en de dashboardgegevens zijn geladen");
When("Nieuw wordt geactiveerd en Backoffice alle hoofdschermen bezoekt");
Then("dezelfde gegevens blijven staan in Nieuw en na terugschakelen naar Klassiek");
Given("een medewerkerdashboard met geladen urenstatus");
When("de medewerker Nieuw activeert en via de bento naar Mijn uren navigeert");
Then("de dashboardstatus gelijk blijft en Klassiek dezelfde gegevens toont");
Given("Backoffice in de nieuwe skin met minstens twee medewerkers in de verhaallijn");
When("Backoffice de tweede medewerker in de wachtrij aanklikt");
Then("wordt die medewerker geselecteerd en toont het verhaal zijn naam en vier statuskaarten");
Given("de medewerker de nieuwe vormgeving opent op de huidige week");
When("alle werkdagen op deze week uren krijgen behalve de laatste, die bewust leeg blijft, en de week wordt opgeslagen");
Then("heeft de server na een herlaad een eigen dagregel voor de laatste dag bewaard, ook al bleef die op 0 uur");
When("de medewerker naar Mededelingen navigeert");
Then("blijft Nieuw actief en blijft de klassieke sidebar verborgen");
Given("de medewerker inlogt en Nieuw activeert");
When("de medewerker naar Mijn uren gaat");
And("de medewerker naar Mededelingen gaat (bereikbaar via de bel)");
Then("brengt de eigen Home-knop terug naar het dashboard, nog altijd in Nieuw");
Given("de medewerker Nieuw activeert");
When("de flow voor SKIN-H-015 wordt uitgevoerd");
Then("staat de theme-snelknop niet meer op het dashboard");
And("blijft de onderliggende voorkeur bereikbaar en werkend via Voorkeuren");
Given("een gebruiker heeft de nieuwe vormgeving in een pilotomgeving gekozen");
When("dezelfde voorkeur onder het productiebeleid wordt toegepast");
Then("blijft productie klassiek zonder zichtbare pilotschakelaar en blijft TEST wel beschikbaar");
Given("de medewerker de nieuwe vormgeving opent op Mijn uren");
Then("heeft de eerste dag drie snelkeuzeknoppen: 0, 8 en 9");
When("op 8 gevolgd door 0 wordt geklikt");
Given("Backoffice een medewerker met een eigen werkpatroon aanmaakt (dinsdag 6 uur, vrijdag 0 uur)");
When("de medewerker inlogt, Nieuw activeert en Mijn uren opent");
Then("staat dinsdag al op 6 uur en vrijdag op leeg (0 uur), zonder dat er iets is getypt");
When("de week wordt opgeslagen zonder verder iets aan te passen");
Then("heeft de server het patroon zelf bewaard: dinsdag 6 uur, vrijdag expliciet 0 uur");
Given("de medewerker Nieuw activeert en Mijn uren opent op een enkele week");
Then("toont Mijn uren dezelfde kaartjesstijl als de bento, met werkende week-pijlen");
When("Hele maand wordt gekozen");
Then("staat de compacte tabel weer terug, geen kaartjes");
And("in Klassiek blijft Mijn uren altijd de tabel, zonder kaartjes of pijlen");
Given("de medewerker Nieuw activeert op het Dashboard");
When("op het Klanturenstaat-blok wordt geklikt");
Then("klapt het blok open, blijft het Dashboard actief en verhuist het echte paneel erin");
When("er nogmaals op wordt geklikt");
Then("klapt het blok weer dicht en staat het paneel terug op zijn vaste plek");
When("het blok weer wordt geopend en daarna naar Mijn uren wordt genavigeerd");
Then("staat het paneel weer op zijn vaste plek op Mijn uren en is het daar gewoon zichtbaar");
