// Navigation-only mapping for timesheets-api.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/timesheet-write.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker is ingelogd");
When("een herhaalbare schrijfbare testperiode is geselecteerd");
Then("save_draft werkt en zet status op draft");
Then("read back van draft bevat dagregels en auditdata");
When("submit wordt uitgevoerd met expected_version");
Then("een ingediende urenstaat kan worden bewerkt en opnieuw ingediend");
And("cleanup: sessie sluiten voor testisolatie");
Given("een ingelogde medewerker");
When("de medewerker een andere employee_id probeert te schrijven");
Then("wordt met Playwright-assertions bevestigd dat employee mag geen andere medewerker schrijven");
When("de write zonder CSRF-token wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat write zonder csrf geeft 403");
Given("er is geen actieve sessie");
When("een write zonder sessie wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat write zonder sessie geeft 401");
When("de medewerker een ongeldige payload verstuurt");
Then("wordt met Playwright-assertions bevestigd dat ongeldige payload geeft 400");
