// Navigation-only mapping for time-registration.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/timesheet-write.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../timesheet-write.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker is ingelogd");
When("een herhaalbare schrijfbare testperiode is geselecteerd");
Then("save_draft werkt en zet status op draft");
Then("read back van draft bevat dagregels en auditdata");
When("submit wordt uitgevoerd met expected_version");
Then("is een ingediende urenstaat op slot en blijft hij ongewijzigd");
And("cleanup: sessie sluiten voor testisolatie");
Then("slaat een eerste opslag dag 1 (8 uur) en dag 2 (bewust 0 uur) op (week A)");
When("een tweede opslag alleen dag 1 (opnieuw, uren > 0) en dag 8 (nieuwe week B) meestuurt, dag 2 blijft nu weg");
Then("bevat de opgeslagen urenstaat alle drie de dagen, de bewuste 0-uur-dag 2 uit week A is niet gewist");
Given("een ingelogde medewerker");
When("de medewerker een andere employee_id probeert te schrijven");
Then("wordt met Playwright-assertions bevestigd dat employee mag geen andere medewerker schrijven");
When("de write zonder CSRF-token wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat write zonder csrf geeft 403");
Given("er is geen actieve sessie");
When("een write zonder sessie wordt verstuurd");
Then("wordt met Playwright-assertions bevestigd dat write zonder sessie geeft 401");
When("de medewerker een ongeldige payload verstuurt");
Then("wordt met Playwright-assertions bevestigd dat ongeldige payload geeft 400");
Given("een ingelogde medewerker met een schrijfbare periode");
When("elke ongeldige dagregel wordt verstuurd");
Then("bestaat er nog geen urenstaat voor die periode");
Given("een medewerker met een opgeslagen concept-urenstaat");
When("een tweede save_draft dezelfde versie gebruikt nadat de eerste die al heeft opgehoogd");
Then("houdt de opgeslagen rij de eerste waarden");
