// Navigation-only mapping for correction-approval-ui.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/timesheet-review-ui.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../timesheet-review-ui.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker een urenstaat indient in de browser");
When("de administrator een correctieverzoek plaatst");
Then("ziet de medewerker het correctieverzoek en dient opnieuw in");
And("de administrator keurt de herindiening goed");
Then("ziet de medewerker de eindstatus Goedgekeurd");
When("de administrator de goedkeuring met reden intrekt");
Then("opent de medewerker de dashboardcorrectie en kan opnieuw indienen");
Given("medewerker opent een ingediende urenstaat");
When("de flow voor TS-REV-UI-H-009 wordt uitgevoerd");
Then("zijn invoer en indienactie vergrendeld en wacht de medewerker op Backoffice");
Given("medewerker opent een goedgekeurde urenstaat");
When("de flow voor TS-REV-UI-H-010 wordt uitgevoerd");
Then("is de indienknop verborgen en staat er een statusmelding");
Given("de ingelogde localhostomgeving een lokaal demo-record zonder serverversie toont");
When("Backoffice Marc met een concrete toelichting terugstuurt");
Then("wordt de lokale status bijgewerkt zonder ongeldige serverwrite");
Given("Backoffice een goedgekeurde maand met definitieve factuur bekijkt");
When("de server heropenen wegens facturatie weigert");
Then("blijft de maand goedgekeurd en krijgt Backoffice een duidelijke blokkade");
When("de administrator de urencontrole opent");
Then("ziet de administrator de exacte dag- en weektotalen van de medewerker");
