// Navigation-only mapping for correction-approval-workflow.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/timesheet-review-flow.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.
/// <reference path="../timesheet-review-flow.spec.ts" />

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("de medewerker is ingelogd en heeft een schrijfbare testperiode");
When("de medewerker een concept opslaat en daarna indient");
And("de reviewcontext wisselt naar administrator");
Then("een verouderde correctie-aanvraag wordt geblokkeerd met stale-version");
When("de administrator een geldige correctie-aanvraag uitvoert");
Then("een tweede correctie op dezelfde versie wordt geweigerd");
And("de context wisselt terug naar medewerker voor herindiening");
Then("een medewerker mag geen admin-reviewactie uitvoeren");
When("de medewerker na correctie opnieuw indient");
And("de context wisselt opnieuw naar administrator voor goedkeuring");
Then("een verouderde approve-aanvraag wordt geblokkeerd met stale-version");
When("de administrator met juiste versie goedkeurt");
Then("read-back toont approved status met volledige audit- en correctiehistorie");
And("een goedkeuring zonder factuur server-side kan worden heropend voor correctie");
And("cleanup: sessie sluiten voor testisolatie");
Given("een medewerker een urenstaat heeft ingediend in een schrijfbare testperiode");
When("twee beheerders tegelijk dezelfde urenstaat proberen goed te keuren");
Then("wordt met Playwright-assertions bevestigd dat gelijktijdige approve-requests door twee beheerders leveren exact één winnaar");
Given("de medewerker is ingelogd");
When("de medewerker concepten opslaat voor december en de daaropvolgende januari");
Then("wordt met Playwright-assertions bevestigd dat jaarwisseling december naar januari verwerkt urenstaten correct over de jaargrens");
