// Navigation-only mapping for user-management.feature.
// Native Playwright remains the executable source of truth; no Cucumber runner is used.
// Executable test: tests/playwright/user-management.spec.ts
// Generated by npm run docs:sync; executable Playwright remains the source of truth.

export {};

const navigate = (_text: string) => undefined;
const Given = navigate;
const When = navigate;
const Then = navigate;
const And = navigate;
const But = navigate;

// Eenvoudige F12-navigatie; de echte acties en assertions staan in het specbestand hierboven.
Given("een ingelogde admin");
When("de userlijst wordt opgehaald");
Then("wordt met Playwright-assertions bevestigd dat admin ziet alle gebruikers van het bedrijf");
When("de admin een medewerker deactiveert");
Then("is de medewerker daarna inactief");
And("heractiveren werkt ook");
When("force_password_change wordt ingesteld voor een medewerker");
Then("wordt met Playwright-assertions bevestigd dat admin kan force_password_change instellen");
Given("geen sessie");
When("GET users.php wordt aangeroepen");
Then("wordt met Playwright-assertions bevestigd dat anonieme gebruiker krijgt 401 op user-list");
Given("een ingelogde medewerker");
When("GET users.php wordt aangeroepen als medewerker");
Then("wordt met Playwright-assertions bevestigd dat medewerker mag geen gebruikersbeheer uitvoeren");
When("de admin zichzelf probeert te deactiveren");
Then("wordt met Playwright-assertions bevestigd dat admin kan zichzelf niet deactiveren");
Given("een reeds gedeactiveerde medewerker");
When("de admin dezelfde medewerker nogmaals probeert te deactiveren");
Then("wordt met Playwright-assertions bevestigd dat dubbel deactiveren geeft 409");
